name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create env file
        working-directory: BE/functions
        run: 
          touch .env
          echo SERVICE_ACCOUNT_KEY=${{ secrets.SERVICE_ACCOUNT_KEY }} >> .env
          
      - name: Install Firebase dependencies
        working-directory: BE
        run: npm install
        
      - name: Install dependencies
        working-directory: BE/functions
        run: npm install
        
      - name: Deploy to Firebase
        working-directory: BE/functions
        run: npm run deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
     
